// =============================================================================
// UIComponentBinderEditor.cs - UI组件绑定编辑器工具（腾讯级生产标准）
// =============================================================================
// 来源: ShaoNvClient_H02 GoldenEngine.GoldenLuaUIComponentEditor（提炼精华）
// 升级: 去除TMPro/XLua模板等业务依赖，保留核心绑定可视化+代码生成
// =============================================================================

using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

/// <summary>
/// UIComponentBinder 的自定义 Inspector。
/// 提供可视化绑定管理 + Lua View 文件自动生成。
/// </summary>
[CustomEditor(typeof(UIComponentBinder), true)]
public class UIComponentBinderEditor : Editor
{
    private UIComponentBinder _binder;

    private void OnEnable()
    {
        _binder = target as UIComponentBinder;
    }

    public override void OnInspectorGUI()
    {
        serializedObject.Update();

        // 深度查找第一个Button
        EditorGUILayout.PropertyField(serializedObject.FindProperty("IsDeepFindFirstButton"));

        EditorGUILayout.Space();

        // 绑定按钮
        if (GUILayout.Button("执行自动绑定 (Bind)", GUILayout.Height(30)))
        {
            Undo.RecordObject(_binder, "Bind UI Components");
            _binder.Bind();
            EditorUtility.SetDirty(_binder);
            Debug.Log($"[UIComponentBinder] 绑定完成，共 {(_binder.UICompList?.Length ?? 0)} 个组件");
        }

        EditorGUILayout.Space();

        // 显示已绑定的组件列表
        EditorGUILayout.LabelField($"已绑定组件 ({(_binder.UICompList?.Length ?? 0)}):", EditorStyles.boldLabel);

        if (_binder.UICompList != null)
        {
            EditorGUI.indentLevel++;
            foreach (var item in _binder.UICompList)
            {
                EditorGUILayout.BeginHorizontal();
                EditorGUILayout.LabelField(item.CompName, GUILayout.Width(200));
                EditorGUI.BeginDisabledGroup(true);
                EditorGUILayout.ObjectField(item.Comp, typeof(Component), true);
                EditorGUI.EndDisabledGroup();
                EditorGUILayout.EndHorizontal();
            }
            EditorGUI.indentLevel--;
        }

        EditorGUILayout.Space();

        // 生成 Lua View 代码
        EditorGUILayout.BeginHorizontal();
        if (GUILayout.Button("生成 Lua View 代码"))
        {
            GenerateLuaViewCode();
        }
        if (GUILayout.Button("复制绑定列表"))
        {
            CopyBindingList();
        }
        EditorGUILayout.EndHorizontal();

        EditorGUILayout.Space();

        // 定位 Prefab
        if (GUILayout.Button("定位 Prefab"))
        {
            EditorGUIUtility.PingObject(_binder.gameObject);
        }

        serializedObject.ApplyModifiedProperties();
    }

    /// <summary>
    /// 生成 Lua View 绑定代码
    /// </summary>
    private void GenerateLuaViewCode()
    {
        if (_binder.UICompList == null || _binder.UICompList.Length == 0)
        {
            EditorUtility.DisplayDialog("提示", "请先执行自动绑定！", "确定");
            return;
        }

        StringBuilder sb = new StringBuilder();
        string className = _binder.gameObject.name.TrimClone();

        sb.AppendLine($"-- Auto-generated by UIComponentBinderEditor");
        sb.AppendLine($"-- Class: {className}View");
        sb.AppendLine($"-- Generated: {System.DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine();
        sb.AppendLine($"local {className}View = {{}}");
        sb.AppendLine();

        sb.AppendLine($"function {className}View:Init(uiBinder)");
        sb.AppendLine($"    -- [自动化替换占位符,不要删除!!!!]");

        foreach (var item in _binder.UICompList)
        {
            string varName = $"self._{item.CompName}";
            string typeName = UIComponentBinder.GetTypeAbbr(item.Comp);

            if (item.Comp is UnityEngine.UI.Button)
            {
                sb.AppendLine($"    {varName} = self:AddComponent(UIButton, \"{item.Comp.name}\")");
                sb.AppendLine($"    {varName}:SetOnClick(self.On{item.Comp.name}Click, self)");
            }
            else if (item.Comp is UnityEngine.UI.Toggle)
            {
                sb.AppendLine($"    {varName} = self:AddComponent(UIToggle, \"{item.Comp.name}\")");
                sb.AppendLine($"    {varName}:SetOnValueChanged(self.On{item.Comp.name}Changed, self)");
            }
            else
            {
                sb.AppendLine($"    {varName} = self:AddComponent(UI{typeName}, \"{item.Comp.name}\")");
            }
        }

        sb.AppendLine($"end");
        sb.AppendLine();
        sb.AppendLine($"function {className}View:OnDestroy()");
        foreach (var item in _binder.UICompList)
        {
            sb.AppendLine($"    self._{item.CompName} = nil");
        }
        sb.AppendLine($"end");
        sb.AppendLine();
        sb.AppendLine($"return {className}View");

        // 保存到文件
        string savePath = EditorUtility.SaveFilePanel("保存 Lua View", Application.dataPath, $"{className}View.lua", "lua");
        if (!string.IsNullOrEmpty(savePath))
        {
            File.WriteAllText(savePath, sb.ToString());
            AssetDatabase.Refresh();
            EditorUtility.DisplayDialog("成功", $"Lua View 已生成:\n{savePath}", "确定");
        }
    }

    /// <summary>
    /// 复制绑定列表到剪贴板
    /// </summary>
    private void CopyBindingList()
    {
        if (_binder.UICompList == null) return;

        StringBuilder sb = new StringBuilder();
        foreach (var item in _binder.UICompList)
        {
            sb.AppendLine($"{item.CompName}\t{UIComponentBinder.GetTypeAbbr(item.Comp)}\t{item.Comp?.GetType().Name}");
        }

        GUIUtility.systemCopyBuffer = sb.ToString();
        Debug.Log("[UIComponentBinder] 绑定列表已复制到剪贴板");
    }
}
